AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - puma-metrics.gemspec

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Exclude:
    - lib/puma/metrics/parser.rb

Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/MissingRespondToMissing:
  Exclude:
    - lib/puma/metrics/parser.rb
