AllCops:
  TargetRubyVersion: 2.2

Naming/FileName:
  Exclude:
    - puma-metrics.gemspec

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
Style/MethodMissingSuper:
  Exclude:
    - lib/puma/metrics/parser.rb
Style/MissingRespondToMissing:
  Exclude:
    - lib/puma/metrics/parser.rb
