name: test
on: [push]
jobs:
  test:
    name: on ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@master
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rake
    - run: bundle exec overcommit --sign
    - env:
        GIT_AUTHOR_NAME: John Doe
        GIT_AUTHOR_EMAIL: johndoe@example.com
      run: bundle exec overcommit --run
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6']
