name: steps
on: [push]
jobs:
  test:
    name: test on ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@master
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: gem install bundler
    - run: bundle install
    - run: bundle exec rake
    - run: bundle exec overcommit --sign
    - env:
        GIT_AUTHOR_NAME: John Doe
        GIT_AUTHOR_EMAIL: johndoe@example.com
      run: bundle exec overcommit --run
    strategy:
      matrix:
        ruby: ['2.6', '2.7', '3.0']
  deploy:
    if: github.ref == 'refs/heads/master'
    name: to rubygems
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@master
      with:
        ruby-version: 3.0
    - env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
